#!/usr/bin/env bash
# Sets up a Linux -> arm64 iOS cross toolchain without needing Xcode or a Mac.
#
#   * clang/lld  : provided by the `ziglang` PyPI wheel (`zig cc` is a real clang driver
#                  with a Mach-O linker built in, so no Apple `ld64` needed)
#   * iOS SDK    : theos/sdks (headers + .tbd stubs)
#   * fakesign   : tools/fakesign.py (pure python ad-hoc CMS-less signer, replaces ldid)
#
# Everything lands in .toolchain/ which is git-ignored.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TC="$ROOT/.toolchain"
SDK_VERSION="${SDK_VERSION:-16.5}"

mkdir -p "$TC"

log() { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m==>\033[0m %s\n' "$*"; }

# ---------------------------------------------------------------- zig / clang
if [ ! -x "$TC/zig/zig" ]; then
	log "Installing zig (clang + Mach-O lld) from PyPI..."
	python3 -m venv "$TC/venv"
	"$TC/venv/bin/pip" install --quiet --upgrade pip
	"$TC/venv/bin/pip" install --quiet ziglang
	ZIGDIR="$("$TC/venv/bin/python" -c 'import ziglang, os; print(os.path.dirname(ziglang.__file__))')"
	ln -sfn "$ZIGDIR" "$TC/zig"
fi
log "zig $("$TC/zig/zig" version)"

# ------------------------------------------------------------------- iOS SDK
SDK="$TC/sdks/iPhoneOS${SDK_VERSION}.sdk"
if [ ! -d "$SDK" ]; then
	log "Fetching iOS SDKs (theos/sdks, ~1.5G checkout, one time)..."
	rm -rf "$TC/sdks"
	git clone --depth 1 https://github.com/theos/sdks.git "$TC/sdks"
fi
[ -d "$SDK" ] || { echo "SDK $SDK missing after clone"; exit 1; }
log "SDK: $SDK"

# ------------------------------------------------------------------ fakesign
if ! python3 -c 'import sys; sys.exit(0)'; then
	echo "python3 required"; exit 1
fi
log "fakesign: $ROOT/tools/fakesign.py (no ldid needed)"

cat > "$TC/env.sh" <<EOF
# generated by tools/setup-toolchain.sh
export TX_TOOLCHAIN="$TC"
export TX_SDK="$SDK"
export TX_ZIG="$TC/zig/zig"
export TX_CC="$TC/zig/zig cc"
EOF

log "Done. Build with:  make        (or: make ipa)"
